### ISSUE TITLE
Broken Hyperlinks in Developer Guide

### ISSUE THREAD

**Issue by i2y4n** [enyojs/enyo-docs#21]
> Not Found
> 
> The requested URL /docs/latest/developer-guide/building-apps/performance/performance.html was not found on this server.
> 
> Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

http://enyojs.com/docs/latest/developer-guide/building-apps/performance/performance.html

http://enyojs.com/docs/latest/developer-guide/design.html

**Comment by webOS101** [comment]
It would be super-handy if you could provide the pages that linked to those.  I think I have found them.  Performance and design were placeholders and I just removed them from the index for now.  Thanks for the report!

**Comment by i2y4n** [comment]
Sorry forgot to include that.

The links were here [http://enyojs.com/docs/latest/developer-guide/index.html](http://enyojs.com/docs/latest/developer-guide/index.html). Looks like you got them.
