### ISSUE TITLE
API URLs in published docs don't match source

### ISSUE THREAD

**Issue by bbito** [enyojs/enyo-docs#27]
It looks like something went wrong with the URLs in the published tutorial at: https://enyojs.com/docs/latest/developer-guide/getting-started/moonstone-app-tutorial.html
Several URLs that should read `api.flickr.com` are shown as `api.com`

However the github source still shows the correct flickr URLs:
https://github.com/enyojs/enyo-docs/blob/master/developer-guide/getting-started/moonstone-app-tutorial.md
See:
http://forums.enyojs.com/discussion/2637/error-on-tutorial-building-a-moonstone-app

**Comment by webOS101** [comment]
The 2.6+ docs are build from this branch:

https://github.com/enyojs/enyo-docs/blob/2.6.0-dev/developer-guide/getting-started/moonstone-app-tutorial.md

The error exists on those pages.  Pull requests welcomed!

**Comment by webOS101** [comment]
I just pushed an update to the docs thanks to your PR!  Should be good now.
